import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

const InterFont = Inter({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${InterFont.classname} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <Navbar/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
